name:                havoc
version:             0.1.0.0
license:             BSD3
author:              "Alex Collins"
maintainer:          "atcollins@pm.me"
copyright:           "2019 Alex Collins"

extra-source-files:
- README.md

description:         Please see the README

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    - -Wall
  dependencies:
    - aeson
    - base >=4.7 && <5
    - bytestring
    - binary
    - case-insensitive
    - http-client
    - http-reverse-proxy
    - http-types
    - hslogger
    - optparse-generic
    - mtl
    - random
    - stm
    - time
    - wai
    - warp

executables:
  havoc:
    main:                Main.hs
    source-dirs:         app
    cc-options: -static
    ld-options: -static -pthread
    ghc-options:
    - -Wall
    - -O2
    - -static
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - async
    - bytestring
    - optparse-generic
    - havoc
    - hslogger
    - raw-strings-qq
    - text
    - havoc

tests:
  havoc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - async
    - bytestring
    - havoc
    - hspec
    - hspec-discover
    - hspec-wai
    - http-client
    - http-types
    - time
    - wai
    - warp
